### PR TITLE
rework section on clients and add overview table

### PR DESCRIPTION
**Pull request by rcannood**
Hello Ellis!

I reworked some text on packages providing R interfaces to the Docker CLI. I also added a table which could be useful for readers to decide on which package to use. The format of the table is a bit basic, but this can be adjusted as we go along.

Screenshot from 2019-12-07 02-06-26

Feel free to suggest or make changes! :)

Robrecht

### CODE REVIEW

**Comment by rcannood** [comment]
Also, I might have missed some essential functionality provided by any of these packages. Feel free to add them! :)

**Comment by hongooi73** [comment]
Hey, thanks for doing this. Just one change: AzureContainers also lets you build an image. I'd add this to the PR but I don't know how to navigate the maze of forks, lol.

**Comment by rcannood** [comment]
Haha! When i was making the PR I was thinking exactly this; if @Hong-Revo wants to make changes, they should be sent in PR to me, but what if @thebioengineer in the meantime merges this PR...

To make things easier, you could press the Edit button on [this page](https://github.com/rcannood/rockerverse-paper/blob/feature/clients/manuscript.Rmd) and edit the things you want. Or post the suggested changes in this thread :)

**Comment by rcannood** [comment]
Update: I merged @thebioengineer's PR into nuest master branch, making this PR irrelevant. I'm going to close it.

**Comment by thebioengineer** [comment]
@rcannood I like the edits you made! Are you planning on opening another pull request for edits to the master branch with these edits? I was thinking about adding a table like that to the section as well.

**Comment by thebioengineer** [comment]
And now I see you did, never mind!

**Comment by rcannood** [comment]
;-)

**Pull request closed without merging**
